-- ============================================================================
-- H2 schema (PostgreSQL compatibility mode).
-- Replaces Prisma `_db_push()` / `schema.prisma` as the DDL owner.
-- Target: jdbc:h2:file:...;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
--
-- Timestamp columns are portable (no SQLite julianday/strftime):
--   created_at    -> epoch milliseconds (Double in JPA)
--   created_at_hk -> 'YYYY-MM-DD HH24:MI:SS' in UTC+8
-- ============================================================================

-- ---------------------------------------------------------------
-- application_state
-- ---------------------------------------------------------------
CREATE TABLE application_state (
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_opened_folder_id INT,
    selected_aiprofile_id INT,
    dark_mode             BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk         VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);

-- ---------------------------------------------------------------
-- scripts_folder
-- ---------------------------------------------------------------
CREATE TABLE scripts_folder (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_level VARCHAR(255) NOT NULL DEFAULT 'USER',
    name         VARCHAR(255) NOT NULL,
    ordering     INT NOT NULL,
    created_at   DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX scripts_folder_id_idx ON scripts_folder (id);

-- ---------------------------------------------------------------
-- shell_script
-- ---------------------------------------------------------------
CREATE TABLE shell_script (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_editing   BOOLEAN NOT NULL DEFAULT FALSE,
    is_markdown  BOOLEAN NOT NULL DEFAULT FALSE,
    name         VARCHAR(255) NOT NULL,
    command      VARCHAR(1000000) NOT NULL,
    ordering     INT NOT NULL,
    locked       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS'),
    show_shell   BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX shell_script_id_idx ON shell_script (id);

-- ---------------------------------------------------------------
-- workspace
-- ---------------------------------------------------------------
CREATE TABLE workspace (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    ordering     INT NOT NULL,
    created_at   DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX workspace_id_idx ON workspace (id);

-- ---------------------------------------------------------------
-- historical_shell_script
-- ---------------------------------------------------------------
CREATE TABLE historical_shell_script (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shell_script_id INT NOT NULL,
    execution_time  DOUBLE PRECISION NOT NULL,
    created_at      DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk   VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX historical_shell_script_shell_script_id_idx ON historical_shell_script (shell_script_id);

-- ---------------------------------------------------------------
-- event (audit log)
-- ---------------------------------------------------------------
CREATE TABLE event (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         VARCHAR(255) NOT NULL,
    created_at         DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk      VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS'),
    event_type         VARCHAR(255) NOT NULL,
    event              VARCHAR(1000000) NOT NULL,
    request_user_email VARCHAR(255) NOT NULL,
    success            BOOLEAN NOT NULL DEFAULT TRUE,
    failure_reason     VARCHAR(1000000) NOT NULL DEFAULT '',
    event_order        INT NOT NULL DEFAULT 1
);

-- ---------------------------------------------------------------
-- ai_profile / script_ai_config / model_config
-- ---------------------------------------------------------------
CREATE TABLE ai_profile (
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(255) NOT NULL,
    description            VARCHAR(1000000) NOT NULL,
    selected_model_config_id INT,
    created_at             DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk          VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE script_ai_config (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled_ai_search BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk     VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE model_config (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    model_source VARCHAR(255) NOT NULL DEFAULT 'AZURE_OPENAI',
    created_at   DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);

-- ---------------------------------------------------------------
-- Join tables
-- ---------------------------------------------------------------
CREATE TABLE rel_scriptsfolder_shellscript (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scripts_folder_id INT NOT NULL,
    shell_script_id   INT NOT NULL,
    created_at        DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk     VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX rel_scriptsfolder_shellscript_shell_script_id_scripts_folde_key
    ON rel_scriptsfolder_shellscript (shell_script_id, scripts_folder_id);
CREATE INDEX rel_scriptsfolder_shellscript_scripts_folder_id_idx ON rel_scriptsfolder_shellscript (scripts_folder_id);
CREATE INDEX rel_scriptsfolder_shellscript_shell_script_id_idx ON rel_scriptsfolder_shellscript (shell_script_id);

CREATE TABLE rel_folder_folder (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_folder_id INT NOT NULL,
    child_folder_id  INT NOT NULL,
    created_at       DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk    VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX rel_folder_folder_parent_folder_id_child_folder_id_key
    ON rel_folder_folder (parent_folder_id, child_folder_id);
CREATE INDEX rel_folder_folder_parent_folder_id_idx ON rel_folder_folder (parent_folder_id);
CREATE INDEX rel_folder_folder_child_folder_id_idx ON rel_folder_folder (child_folder_id);

CREATE TABLE rel_workspace_folder (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id INT NOT NULL,
    folder_id    INT NOT NULL,
    created_at   DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX rel_workspace_folder_workspace_id_folder_id_key
    ON rel_workspace_folder (workspace_id, folder_id);
CREATE INDEX rel_workspace_folder_workspace_id_idx ON rel_workspace_folder (workspace_id);
CREATE INDEX rel_workspace_folder_folder_id_idx ON rel_workspace_folder (folder_id);

CREATE TABLE rel_shellscript_aiconfig (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shell_script_id     INT NOT NULL,
    script_ai_config_id INT NOT NULL
);

CREATE TABLE rel_aiprofile_modelconfig (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_profile_id   INT NOT NULL,
    model_config_id INT NOT NULL
);

CREATE TABLE rel_aiprofile_aiscriptedtool (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_profile_id       INT NOT NULL,
    ai_scripted_tool_id INT NOT NULL
);

-- ---------------------------------------------------------------
-- AI provider configs
-- ---------------------------------------------------------------
CREATE TABLE azure_model_config (
    id                       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_config_id          INT NOT NULL,
    azure_openai_api_key     VARCHAR(1000000) NOT NULL,
    azure_openai_endpoint    VARCHAR(1000000) NOT NULL,
    azure_openai_api_version VARCHAR(255) NOT NULL,
    azure_openai_model       VARCHAR(255) NOT NULL,
    created_at               DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk            VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE openai_model_config (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_config_id INT NOT NULL,
    openai_api_key  VARCHAR(1000000) NOT NULL,
    openai_model    VARCHAR(255) NOT NULL,
    created_at      DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk   VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE ai_scripted_tool (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    tool_description VARCHAR(1000000) NOT NULL,
    is_enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    shell_script_id  INT NOT NULL,
    created_at       DOUBLE PRECISION NOT NULL DEFAULT DATEDIFF('MILLISECOND', TIMESTAMP '1970-01-01 00:00:00', CURRENT_TIMESTAMP),
    created_at_hk    VARCHAR(255) NOT NULL DEFAULT TO_CHAR(TIMESTAMPADD('HOUR', 8, CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')
);

-- ---------------------------------------------------------------
-- Workspace status
-- ---------------------------------------------------------------
CREATE TABLE workspace_status (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE rel_workspace_workspacestatus (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_status_id INT NOT NULL,
    workspace_id        INT NOT NULL
);

-- ---------------------------------------------------------------
-- Foreign keys (match Prisma onDelete rules)
-- ---------------------------------------------------------------
ALTER TABLE ai_profile
    ADD CONSTRAINT ai_profile_selected_model_config_id_fkey
    FOREIGN KEY (selected_model_config_id) REFERENCES model_config (id) ON DELETE SET NULL;

ALTER TABLE rel_scriptsfolder_shellscript
    ADD CONSTRAINT rel_scriptsfolder_shellscript_shell_script_id_fkey
    FOREIGN KEY (shell_script_id) REFERENCES shell_script (id) ON DELETE CASCADE;
ALTER TABLE rel_scriptsfolder_shellscript
    ADD CONSTRAINT rel_scriptsfolder_shellscript_scripts_folder_id_fkey
    FOREIGN KEY (scripts_folder_id) REFERENCES scripts_folder (id) ON DELETE CASCADE;

ALTER TABLE rel_folder_folder
    ADD CONSTRAINT rel_folder_folder_parent_folder_id_fkey
    FOREIGN KEY (parent_folder_id) REFERENCES scripts_folder (id) ON DELETE CASCADE;
ALTER TABLE rel_folder_folder
    ADD CONSTRAINT rel_folder_folder_child_folder_id_fkey
    FOREIGN KEY (child_folder_id) REFERENCES scripts_folder (id) ON DELETE CASCADE;

ALTER TABLE rel_workspace_folder
    ADD CONSTRAINT rel_workspace_folder_workspace_id_fkey
    FOREIGN KEY (workspace_id) REFERENCES workspace (id);
ALTER TABLE rel_workspace_folder
    ADD CONSTRAINT rel_workspace_folder_folder_id_fkey
    FOREIGN KEY (folder_id) REFERENCES scripts_folder (id);

ALTER TABLE rel_shellscript_aiconfig
    ADD CONSTRAINT rel_shellscript_aiconfig_shell_script_id_fkey
    FOREIGN KEY (shell_script_id) REFERENCES shell_script (id) ON DELETE CASCADE;
ALTER TABLE rel_shellscript_aiconfig
    ADD CONSTRAINT rel_shellscript_aiconfig_script_ai_config_id_fkey
    FOREIGN KEY (script_ai_config_id) REFERENCES script_ai_config (id) ON DELETE CASCADE;

ALTER TABLE rel_aiprofile_modelconfig
    ADD CONSTRAINT rel_aiprofile_modelconfig_ai_profile_id_fkey
    FOREIGN KEY (ai_profile_id) REFERENCES ai_profile (id) ON DELETE CASCADE;
ALTER TABLE rel_aiprofile_modelconfig
    ADD CONSTRAINT rel_aiprofile_modelconfig_model_config_id_fkey
    FOREIGN KEY (model_config_id) REFERENCES model_config (id) ON DELETE CASCADE;

ALTER TABLE azure_model_config
    ADD CONSTRAINT azure_model_config_model_config_id_fkey
    FOREIGN KEY (model_config_id) REFERENCES model_config (id) ON DELETE CASCADE;

ALTER TABLE openai_model_config
    ADD CONSTRAINT openai_model_config_model_config_id_fkey
    FOREIGN KEY (model_config_id) REFERENCES model_config (id) ON DELETE CASCADE;

ALTER TABLE ai_scripted_tool
    ADD CONSTRAINT ai_scripted_tool_shell_script_id_fkey
    FOREIGN KEY (shell_script_id) REFERENCES shell_script (id) ON DELETE CASCADE;

ALTER TABLE rel_aiprofile_aiscriptedtool
    ADD CONSTRAINT rel_aiprofile_aiscriptedtool_ai_profile_id_fkey
    FOREIGN KEY (ai_profile_id) REFERENCES ai_profile (id) ON DELETE CASCADE;
ALTER TABLE rel_aiprofile_aiscriptedtool
    ADD CONSTRAINT rel_aiprofile_aiscriptedtool_ai_scripted_tool_id_fkey
    FOREIGN KEY (ai_scripted_tool_id) REFERENCES ai_scripted_tool (id) ON DELETE CASCADE;

ALTER TABLE rel_workspace_workspacestatus
    ADD CONSTRAINT rel_workspace_workspacestatus_workspace_status_id_fkey
    FOREIGN KEY (workspace_status_id) REFERENCES workspace_status (id) ON DELETE CASCADE;
ALTER TABLE rel_workspace_workspacestatus
    ADD CONSTRAINT rel_workspace_workspacestatus_workspace_id_fkey
    FOREIGN KEY (workspace_id) REFERENCES workspace (id) ON DELETE CASCADE;
